### PR TITLE
Delete hacktoberfest related content from GL website

### PR DESCRIPTION
**Pull request by anajsana**
This commmit deletes hacktoberfest related content at index.html page

Signed-off-by: anajs <anitajs95@gmail.com>

### CODE REVIEW

**Review by sduenas — CHANGES_REQUESTED** [review]
You should remove `events.html` file if we're not going to use it anymore. Also, set the tittle of this PR as the title of the commit and the current title of the commit as the description.

**Comment by anajsana** [comment]
> You should remove `events.html` file if we're not going to use it anymore. Also, set the tittle of this PR as the title of the commit and the current title of the commit as the description.

Events.html was created to be used for upcoming events where GL might be part of. That's why is important to keep it.

**Comment by sduenas** [comment]
> > You should remove `events.html` file if we're not going to use it anymore. Also, set the tittle of this PR as the title of the commit and the current title of the commit as the description.
> 
> Events.html was created to be used for upcoming events where GL might be part of. That's why is important to keep it.

If nothing references it, why should we keep it? Information there is old.

**Comment by GeorgLink** [comment]
> Events.html was created to be used for upcoming events where GL might be part of. That's why is important to keep it.

You can always find the Events.html again in the GitLog: https://github.com/chaoss/grimoirelab/commit/f9642237380f4a75f5335103270110ea9d488574

**Comment by vchrombie** [comment]
A similar PR https://github.com/chaoss/grimoirelab/pull/425 is already merged and changes are reflected on the website. So, I think we can close this PR.

**Pull request closed without merging**
