### PR TITLE
Remove FINOS Meetings support

### PR DESCRIPTION
**Pull request by sduenas**
The backend has been removed from the stack of the platform. This commits also removes it from the metapackage.

### CODE REVIEW

**Comment by vchrombie** [comment]
Related to https://github.com/chaoss/grimoirelab/issues/468

**Comment by vchrombie** [comment]
Hi @sduenas, I think we are in the right direction for removing the finos backend. I just wanted to check if there is any more work pending.

The perceval backend is archived, enrichers are removed from elk and the configurations are removed from sirmordred. Do we have the visualizations in sigils?

**Comment by sduenas** [comment]
> Hi @sduenas, I think we are in the right direction for removing the finos backend. I just wanted to check if there is any more work pending.
> 
> The perceval backend is archived, enrichers are removed from elk and the configurations are removed from sirmordred. Do we have the visualizations in sigils?

There aren't any visualizations so this is the last PR we have to remove it.

**Comment by jjmerchante** [comment]
LGTM

**Pull request merged**
