### PR TITLE
Make aliases.json consistent with setup.cfg

### PR DESCRIPTION
**Pull request by hmitsch**
See https://github.com/chaoss/grimoirelab/issues/404#issuecomment-760512973

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @hmitsch, thanks for the PR. The CHAOSS Charter requires that contributions are accompanied by a Developer Certificate of Origin sign-off. For ensuring it, a bot checks all incoming commits. We need the sign-off to merge the PR.

I can help you with it.
```
git clone https://github.com/hmitsch/grimoirelab
git checkout patch-1
git commit --amend -s
git push -f origin patch-1
```

Let us know if you need more help. We are happy to help you. :slightly_smiling_face:

**Comment by hmitsch** [comment]
Thanks, @vchrombie, hope this is fine now.

**Comment by vchrombie** [comment]
> Thanks, @vchrombie, hope this is fine now.

LGTM, thanks for your effort. :slightly_smiling_face: 
I will leave this to @sduenas's review. He will check it in a few days.

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
