### PR TITLE
[docker-compose] Update images to ES/Kibiter 6.8

### PR DESCRIPTION
**Pull request by valeriocos**
This code updates the docker-compose files by changing the elasticsearch and kibiter sections
to use the images for ES/Kibiter 6.8.

### CODE REVIEW

**Comment by vchrombie** [comment]
I was waiting for this PR to see the new Kibiter. :smile:

**Comment by valeriocos** [comment]
Hi @vchrombie ,

> I will try the new version and update the screenshot in the README.md

Perfect thanks

> do you think we need to update this in the sirmordred repo too?

Feel free to review the PR in mordred: https://github.com/chaoss/grimoirelab-sirmordred/pull/474.

We could update also the images in the troubleshooting and how to sections. If you want, we can split the work or wait for GSoD, wdyt? 
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#troubleshooting-
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#how-to-

**Comment by vchrombie** [comment]
Hi @valeriocos 

> Feel free to review the PR in mordred: [chaoss/grimoirelab-sirmordred#474](https://github.com/chaoss/grimoirelab-sirmordred/pull/474).

Sure, I will do it in a while.

> We could update also the images in the troubleshooting and how to sections. If you want, we can split the work or wait for GSoD, wdyt?
> 
>     * https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#troubleshooting-
> 
>     * https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#how-to-

A few candidates have contacted me showing interest in the GrimoireLab GSoD idea. I have replied them to mail to the grimoirelab mailing list. This could be a good-start for them if they wish to contribute and participate in the program. Let's see if anyone wishes to contribute. We can help them if they get stuck. WDYT?

**Comment by valeriocos** [comment]
> A few candidates have contacted me showing interest in the GrimoireLab GSoD idea. I have replied them to mail to the grimoirelab mailing list. This could be a good-start for them if they wish to contribute and participate in the program. Let's see if anyone wishes to contribute. We can help them if they get stuck. WDYT?

Good idea!

**Pull request merged**
