### PR TITLE
Changing `GitHub No Replay` to `GitHub No Reply`

### PR DESCRIPTION
**Pull request by ChrisCarini**

### CODE REVIEW

**Comment by vchrombie** [comment]
I think the change makes sense to me.

@ChrisCarini do you mind fixing the sign-off issue?
https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#dco-and-sign-off-for-contributions

You can amend the commit and force push the branch. Please let me know if you need any help.

**Comment by ChrisCarini** [comment]
@vchrombie done!

**Review by vchrombie — APPROVED** [review]
LGTM!
Thanks for the PR @ChrisCarini

**Comment by ChrisCarini** [comment]
@vchrombie - No problem! Now I just need to figure out how to get grimoirelab up and running 🤔 (have yet to be successful 😞)...

**Comment by vchrombie** [comment]
You can use the grimoirelab tutorial
https://chaoss.github.io/grimoirelab-tutorial/getting-started

It's fairly straightforward simple if you are using the docker-compose method (explained in the tutorial)

Please let us know if you need any help

**Pull request merged**
