### PR TITLE
[docker] Generate docker images for ARM64 architecture

### PR DESCRIPTION
**Pull request by jjmerchante**
This PR updates the Docker workflow to generate images for amd64 and arm64.

Related to https://github.com/chaoss/grimoirelab/issues/550

### CODE REVIEW

**Comment by loganknecht** [comment]
Very excited about this!

**Comment by loganknecht** [comment]
Hello - and Happy Halloween! 🎃 

Do you know if this ended up working? I'm very excited for it to be merged and to try it out!

**Review by sduenas — APPROVED** [review]
LGTM

**Comment by sduenas** [comment]
@loganknecht the image is ready in https://hub.docker.com/r/grimoirelab/grimoirelab/tags

Can you try it and check if it works?

**Pull request merged**
