### PR TITLE
[docker/third-party] Fix nomos installation

### PR DESCRIPTION
**Pull request by valeriocos**
This code removes the Dockerfile-fossology and related entrypoint, and propose to install nomos using the release 3.8.0 available at https://github.com/fossology/fossology/releases

Documentation has been updated accordingly.

Replaces https://github.com/chaoss/grimoirelab/pull/317
Fixes https://github.com/chaoss/grimoirelab/issues/306

### CODE REVIEW

**Comment by valeriocos** [comment]
@vchrombie feel free to review it to, you should follow the new instruction in the third-party/README.md, thanks

**Comment by vchrombie** [comment]
Hi @valeriocos 
I have tested your PR on my local machine. The new installation works perfectly fine.
You can find the complete log here, [dockerfile-grimoirelab-3p-console-log](https://gist.github.com/vchrombie/1c2b0937faad19d0730ef1ba0d9c5590#file-dockerfile-grimoirelab-3p-console-log).

The problem which you have shared [#317 (comment)](https://github.com/chaoss/grimoirelab/pull/317#issuecomment-633069581) doesn't seem to persist anymore.

I just have a small nit. I found a really small typo in the commit message. :grimacing: 
```
This code removes the Dockerfile-fossology and related
entrypoint, and propose to install nomos using the
release 3.8.0 available at
https://github.com/fossology/fossology/releases

Documentatio has been updated accordingly. <--- Documentation

Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
```

Feel free to close the PR #317 once this is merged. :smiley:

**Comment by valeriocos** [comment]
Thank you @vchrombie for the feedback, I have corrected the typo.

Can you follow the steps from `Copy/replace the following files ...` at https://github.com/chaoss/grimoirelab/tree/master/third-party#preparation and https://github.com/chaoss/grimoirelab/tree/master/third-party#execution.

Once you have started the container, you can:
- enter in the container (docker exec -it <name-of-the-container> bash)
- check that in the `/logs/all.log` file there is no error message (grep ERROR)

You can also check that the colic enriched index in elasticsearch (available at localhost:9000) exists and contains data.

Thanks! :)

**Comment by vchrombie** [comment]
Hi @valeriocos 
I have tested the execution too as you said and got you the results.

> Can you follow the steps from `Copy....

The execution went fine, es mariadb kibiter all were launched. You can check the full [execution console log](https://gist.github.com/vchrombie/1c2b0937faad19d0730ef1ba0d9c5590#file-preparation-and-execution). Once the container is completely up, the git github cocom colic indexes updates regularly. 

es working fine
Screenshot_20200524_004313

kibiter working fine
Screenshot_20200524_023018

> You can also check that the colic enriched index in elasticsearch (available at localhost:9000) exists and contains data.

colic data (also checked in es too)
Screenshot_20200524_023259

colic dashboard (had to refresh the index once though)
Screenshot_20200524_023319

But, I found a few `ERRORS` in the log. So, went for further analysis. 

> Once you have started the container, you can:
>     * enter in the container (docker exec -it  bash)
>     * check that in the `/logs/all.log` file there is no error message (grep ERROR)

```
p0tt3r@wand ~                                                                                                   [2:41:16] 
> $ docker exec -it dd5c96502267 bash                                                                                    
grimoirelab@dd5c96502267:~$ cat kibana.log | grep ERROR
grimoirelab@dd5c96502267:~$ cat /logs/all.log | grep ERROR
2020-05-23 20:48:26,121 - grimoire_elk.elk - ERROR - Error feeding raw from colic (https://github.com/chaoss/grimoirelab-toolkit): git command - Cloning into bare repository '/home/grimoirelab/.graal/repositories/https://github.com/chaoss/grimoirelab-toolkit-git'...
2020-05-23 20:48:26,121 - grimoire_elk.elk - ERROR - Error feeding raw from cocom (https://github.com/chaoss/grimoirelab-toolkit): git command - Cloning into bare repository '/home/grimoirelab/.graal/repositories/https://github.com/chaoss/grimoirelab-toolkit-git'...
2020-05-23 20:54:21,257 - grimoire_elk.elk - ERROR - Error feeding raw from colic (https://github.com/chaoss/grimoirelab-toolkit): git command - Cloning into bare repository '/home/grimoirelab/.graal/repositories/https://github.com/chaoss/grimoirelab-toolkit-git'...
2020-05-23 20:54:21,258 - grimoire_elk.elk - ERROR - Error feeding raw from cocom (https://github.com/chaoss/grimoirelab-toolkit): git command - Cloning into bare repository '/home/grimoirelab/.graal/repositories/https://github.com/chaoss/grimoirelab-toolkit-git'...
2020-05-23 20:59:34,981 - grimoire_elk.elk - ERROR - Error feeding raw from cocom (https://github.com/chaoss/grimoirelab-toolkit): git command - fatal: destination path '/home/grimoirelab/.graal/repositories/https://github.com/chaoss/grimoirelab-toolkit-git' already exists and is not an empty directory.
grimoirelab@dd5c96502267:~$ ls
jadolint.jar  kibana.log  kibiter-6.1.4-1-linux-x86_64
```

I don't think these are some major errors, not sure though. :thinking: 

I found these in the [execution console log](https://gist.github.com/vchrombie/1c2b0937faad19d0730ef1ba0d9c5590#file-preparation-and-execution) too. You can check if needed.
Let me know if I need to some more analysis. :smiley:

**Comment by valeriocos** [comment]
Thank you @vchrombie for the detailed review!

> I don't think these are some major errors, not sure though. thinking

Yes, I agree with you. Since they are not related to this PR, I opened an issue: https://github.com/chaoss/grimoirelab-graal/issues/95

**Comment by jgbarah** [comment]
Thanks for the patch and the testing. Merging.

**Pull request merged**
