### PR TITLE
Add Cauldron stats to readme

### PR DESCRIPTION
**Pull request by GeorgLink**
First GitHub repo to use the latest Cauldron release feature
to include an image with updated stats in their README.

### CODE REVIEW

**Review by jgbarah — APPROVED** [review]
Looks god to me. Thanks!!

**Comment by GeorgLink** [comment]
I made the image smaller :)

**Comment by sduenas** [comment]
The stats are old because data is not updated in that service since mid May. If we're going to include this, data should be up-to-date.

**Comment by vchrombie** [comment]
Hi @sduenas 

> The stats are old because data is not updated in that service since mid May. If we're going to include this, data should be up-to-date.

I see that the project is updated recently on July 16, and I feel it will be updated regularly from here on. Do you think we can move this forward and merge it?

I think the stats look great in the readme.

**Pull request closed without merging**
