### PR TITLE
[docker] Add logrotate to docker

### PR DESCRIPTION
**Pull request by arnonm-intel**
Add logrotate to docker and set to keep 3 copies of /log/all.log at 100MB each

### CODE REVIEW

**Comment by jgbarah** [comment]
Thanks a lot, @arnonm-intel. Tests are failing because of the DCO thing. Please check ["DCO and Sign-off contributions" in CONTRIBUTING.md](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#dco-and-sign-off-for-contributions).

Now, wrt the patch itself. I like the idea of keeping logs under control, but at the same time I'm a bit reluctant to have it because of the added dependency (on `logrotate`). Anyone else has an opinion on this? (Any further comment by you @arnonm-intel is welcome, of course).

**Comment by arnonm-intel** [comment]
We use the containers to run the stack for months on end. As a result, the log file continues to grow and eventually hits a limit
I saw two options here – either add a rotate functionality to SirMordred, or add it to the container in the simplest way – a logrotate

**Comment by arnonm-intel** [comment]
Signature fixed. Can you retrigger it?

**Comment by jgbarah** [comment]
> Signature fixed. Can you retrigger it?

I'm not seeing new commits with signature... Maybe you didn't push them or something?

**Comment by sduenas** [comment]
Closing this due to inactivity .

**Pull request closed without merging**
