### PR TITLE
Update GrimoireLab website under CHAOSS

### PR DESCRIPTION
**Pull request by jsmanrique**
If we are gonna promote the new website, it needs to have any GrimoireCon info deleted, and the README.md file about how to build it updated.

### CODE REVIEW

**Comment by jgbarah** [comment]
Sorry, @jsmanrique but I miss the rationale. Why should we remove that?

**Comment by jsmanrique** [comment]
Because, I expect that next CHAOSSCon won't be managed from GrimoireLab website. So I expect the GrimoireLab docs website to be based on GrimoireLab related topics.
IMHO current page (with this PR) is a temporary solution while we move to a more docs oriented website, but I might be wrong on this strategy/thought

**Comment by jsmanrique** [comment]
Because, I expect that next CHAOSSCon won't be managed from GrimoireLab website. So I expect the GrimoireLab docs website to be based on GrimoireLab related topics.
IMHO current page (with this PR) is a temporary solution while we move to a more docs oriented website, but I might be wrong on this strategy/thought

**Comment by jgbarah** [comment]
OK, I undestand. Merging.

**Pull request merged**
