### PR TITLE
fix typos to remove  warning logs

### PR DESCRIPTION
**Pull request by eyehwan**
https://github.com/chaoss/grimoirelab/issues/441

Signed-off-by: Yehui Wang <yehui.wang.mdh@gmail.com>

### CODE REVIEW

**Review by sduenas — CHANGES_REQUESTED** [review]
Thanks for the patch. Would you mind to reword your commit message. Please follow the rules that we have. Thank you!

**Comment by eyehwan** [comment]
Sure, just updated.

**Review by sduenas — CHANGES_REQUESTED** [review]
Sorry, I should had been more clear. I think you should explain better this change, for example:

```
Fix typo on lifecycle menu entry

A typo on the menu.yml made unable to access the lifecycle panel using the menu.
This patch also removes the warning logs associated to it.
```
What do you think?

**Comment by eyehwan** [comment]
Thanks @sduenas, just updated.

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
